### ISSUE TITLE
mongo:update/5 not exported

### ISSUE THREAD

**Issue by amtal** [TonyGen/mongodb-erlang#10]
mongo:update(true,true,...) thus not callable.

Upserts with {$inc,...} operations do not appear possible without the export.

Edit: disregard this I am dumb.

**Comment by TonyGen** [comment]
You mean allow multiple insert? I didn't think that made sense.

On Thu, Aug 11, 2011 at 11:48 PM, amtal
reply@reply.github.com
wrote:
