### ISSUE TITLE
Unable to handle binary type 2

### ISSUE THREAD

**Issue by paulbjensen** [TonyGen/mongodb-erlang#11]
StackTrace:

```
exception error: no case clause matching 2
    in function  bson_binary:get_binary/1
```

Root of StackTrace:

```
bson/src/bson_binary.erl:132
```

**Comment by pusewicz** [comment]
Looks like this is the old binary type (which should be supported):

```
subtype ::= "\x00"  Binary / Generic
          | "\x01"  Function
          | "\x02"  Binary (Old)
          | "\x03"  UUID
          | "\x05"  MD5
          | "\x80"  User defined
```

http://bsonspec.org/#/specification

**Comment by TonyGen** [comment]
You must have created that data using an old driver. It's easy to add the case to read (but not write) that type. I will do it in a week or so. Submit a pull-request if you want it sooner.
Cheers,
Tony

**Comment by pusewicz** [comment]
Cool, that would be great, as I only need to read the data. I'll see if I can submit a patch.

**Comment by paulbjensen** [comment]
Closing as this is an old issue.
