### ISSUE TITLE
ets:update_counter fails in mongodb_app:next_requestid()

### ISSUE THREAD

**Issue by mweibel** [TonyGen/mongodb-erlang#13]
Hi,

I don't really know if this is a bug in the driver but maybe you can help me anyway. 
I posted the full question on stackoverflow:

http://stackoverflow.com/questions/9005265/mongodb-erlang-driver-mongodo-fails-because-of-mongodbnext-requestid-etsu

Thanks for checking this out :)
- Michael

**Comment by TonyGen** [comment]
I think you forgot to initialize:

> application:start (mongodb).

See ReadMe at https://github.com/mongodb/mongodb-erlang

**Comment by mweibel** [comment]
Actually I did this. I also tried starting it again directly before I do the mongo:do but that didn't work either :/

**Comment by TonyGen** [comment]
Does following the ReadMe work? If so what are you doing differently?

**Comment by mweibel** [comment]
Well, I don't know what I'm doing differently.. I'll try if I figure it out by checking if the application is really started..

**Comment by mweibel** [comment]
Well well well. Embarassing for me: I copied the built files with ebin/*.beam and didn't copy the .app file too. As a result the app couldn't be started and the ets tables haven't been initialized.
