### ISSUE TITLE
Code is not consistent with API docs.

### ISSUE THREAD

**Issue by soplakanets** [TonyGen/mongodb-erlang#15]
It is very weird, but API docs at http://api.mongodb.org/erlang/mongodb/ document functionality that does not exists in this repo (nor in official (?) mongodb/mongodb-erlang).
Example: API docs document mongo:create_index/3 and mongo:create_index/4 but I can not find them in source code.

**Comment by soplakanets** [comment]
OK, I did some digging in codebase and the issue is that API docs are simply outdated. Any chance you can update them?

**Comment by TonyGen** [comment]
Yeah, sorry the API docs are outdated. This TonyGen repo is no longer the master for the Erlang driver. Please post this issue on the mongodb repo.

**Comment by soplakanets** [comment]
OK, I will repost the issue on mongodb/mongodb-erlang, but please enable issues there.

**Comment by TonyGen** [comment]
Mongo tracks issues at jira.mongodb.org. Select Erlang project.

**Comment by soplakanets** [comment]
https://jira.mongodb.org/browse/ERLANG-24
