### ISSUE TITLE
2d index creation fails

### ISSUE THREAD

**Issue by asabil** [TonyGen/mongodb-erlang#4]
2d index creation fails in mongo:gen_index_name/1 with:
    {badarg,[{erlang,integer_to_list,['2d']},
                             {mongo,'-gen_index_name/1-fun-0-',3},
                             {bson,doc_foldlN,5},
                             {mongo,create_index,3},
                             {soundrop_model_place,init,0},
                             {mongo,do,5}]

When fixing the gen_index_name/1 implementation to accept the '2d' atom, the mongodb server seems to ignore the 2d index for some reason.

**Comment by TonyGen** [comment]
Hi,

Sorry I haven't looked at this yet. I will within a few weeks.

Cheers,
Tony

**Comment by asabil** [comment]
Hi,

Do you have any updates on this ?

**Comment by TonyGen** [comment]
I just committed the fix.
You have to supply <<"2d">> instead of '2d'. The server never uses atoms/symbols because javascript does not have that type.

Cheers,
Tony

**Comment by TonyGen** [comment]
Clarification: The server never uses atoms/symbols for meta-data. Of course, you can use atoms for your own data.

**Comment by asabil** [comment]
Awesome, thank you very much
